# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmament', '0002_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='user_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted by user'),
        ),
        migrations.AddField(
            model_name='case',
            name='user_deleted_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
