# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-01 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firmament', '0003_auto_20160728_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_abbreviation', models.CharField(max_length=64)),
                ('jurisdiction', models.CharField(max_length=24)),
            ],
        ),
        migrations.RenameField(
            model_name='case',
            old_name='page_number',
            new_name='first_page',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='last_page_number',
            new_name='last_page',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='short_name',
            new_name='name_abbreviation',
        ),
        migrations.AlterField(
            model_name='case',
            name='name_abbreviation',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name='case',
            name='status',
        ),
        migrations.AddField(
            model_name='case',
            name='decision_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='docket_number',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='publication_status',
            field=models.CharField(blank=True, choices=[('draft', 'draft'), ('published', 'published'), ('withdrawn', 'withdrawn')], default='draft', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='firmament.Court'),
        ),
    ]
