# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-01 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmament', '0004_auto_20170201_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='short_name',
            new_name='name_abbreviation',
        ),
        migrations.AlterField(
            model_name='court',
            name='jurisdiction',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='name_abbreviation',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
