# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-14 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firmament', '0006_auto_20170209_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 14, 17, 18, 33, 452970, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
